export const comments = [
  {id: 1,
  songId: 424567592,
  songTitle: 'Tiny Dancer',
  artist: 'Elton John',
  comment: 'Hold me closer, Tony Danza',
  fave: false},
  {id: 2,
  songId: 447552822,
  songTitle: 'Pour Some Sugar On Me',
  artist: 'Def Leppard',
  comment: 'Pour some sugar on May',
  fave: false},
  {id: 3,
  songId: 632488,
  songTitle: `It's Gonna Be Me`,
  artist: '*NSYNC',
  comment: `It's gonna be May`,
  fave: false},
  {id: 4,
  songId: 781563062,
  songTitle: `You're The One That I Want`,
  artist: 'John Travolta',
  comment: `You're the wobbly one`,
  fave: false},
  {id: 5,
  songId: 628266,
  songTitle: `Hey Ya!`,
  artist: 'Outkast',
  comment: `Shake it like a polar bear ninja`,
  fave: false},
  {id: 6,
  songId: 136336110,
  songTitle: '24K Magic',
  artist: 'Bruno Mars',
  comment: `Don't believe me, just wash`,
  fave: false},
  {id: 7,
  songId: 119898840,
  songTitle: 'I Just Died in Your Arms Tonight',
  artist: 'Cutting Crew',
  comment: 'I just died in your barn tonight, mustard no mayonnaise instead',
  fave: false},
  {id: 8,
  songId: 940332,
  songTitle: 'Chasing Pavements',
  artist: 'Adele',
  comment: 'Or should I just keep chasing penguins',
  fave: false},
  {id: 9,
  songId: 14552280,
  songTitle: 'My Heart Will Go On',
  artist: 'Céline Dion',
  comment: 'The hot dogs go on and on',
  fave: false},
  {id: 10,
  songId: 4952885,
  songTitle: 'Purple Haze',
  artist: 'Jimi Hendrix',
  comment: `Excuse me while I kiss this guy`,
  fave: false},

]
